apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-locker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secrets-locker
  template:
    metadata:
      labels:
        app: secrets-locker
    spec:
      containers:
      - name: secrets-locker
        image: secrets-locker:latest
        env:
        - name: KMS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: kms-secret
              key: kms_key_id
        ports:
        - containerPort: 5000